export const ActionType = {

    //Cart
    ADD_CART: "ADD_CART",
    REMOVE_CART: "REMOVE_CART",
    CLEAR_CART: "CLEAR_CART",

    //Product
    GET_PRODUCT_REQUEST: "GET_PRODUCT_REQUEST",
    GET_PRODUCT_SUCCESS: "GET_PRODUCT_SUCCESS",
    GET_PRODUCT_FAIL: "GET_PRODUCT_FAIL",

    GET_PRODUCT_DETAILS_REQUEST: "GET_PRODUCT_REQUEST_DETAILS",
    GET_PRODUCT_DETAILS_SUCCESS: "GET_PRODUCT_DETAILS_SUCCESS",
    GET_PRODUCT_DETAILS_FAIL: "GET_PRODUCT_DETAILS_FAIL",
    GET_PRODUCT_DETAILS_RESET: "GET_PRODUCT_DETAILS_RESET",

    //Account
    LOGIN: "LOGIN",
    SIGNUP: "SIGNUP",

    //Catagory

    ADD_CATAGORY: "ADD_CATAGORY",
    ADD_CATAGORY_DETAILS: "ADD_CATAGORY_DETAILS",

    //
    GET_CART: "GET_CART",

    //Order
    GET_ORDER: "GET_ORDER"

}